spring:
  application:
    name: mymall-admin
  datasource:
    url: jdbc:mysql://localhost:3306/mymall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
info:
  company.name: www.abc.com
  company.addr: China Beijin
  company.tel: 1234
  app.name: provider-service
  author: jeason