spring:
  application:
    name: mymall-portal
  rabbitmq:
    host: 39.105.6.8 # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /mall # rabbitmq的虚拟host
    username: mall # rabbitmq的用户名
    password: mall # rabbitmq的密码
    # publisher-confirms: true #如果对异步消息需要回调必须设置为true,设置此属性配置可以确保消息成功发送到交换器
  datasource:
    url: jdbc:mysql://localhost:3306/mymall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
info:
  company.name: www.abc.com
  company.addr: China Beijin
  company.tel: 1234
  app.name: provider-service
  author: jeason